theme: minima
title: "Chadd's Blog"
author: Chaddrick Winston
email: chaddrick.winston@outlook.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my Microsoft Systems and Software Academy Blog! I will be posting entries about my experience in the program
 and plan to share my thoughts and any tips that I come along. So sit back and enjoy the ride...I know I will!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ckwinst # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
